name: genql-cli Npm Package

on:
  push:
    # branches:
    #   - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13'
      - run: npm i -g npm@latest
      - name: Bump version
        if: contains(['refs/heads/master', 'refs/heads/beta'], github.ref)
        uses: remorses/bump-version@js
        with:
          version_file: VERSION
          ignore: dist, esm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
        if: contains(['refs/heads/master', 'refs/heads/beta'], github.ref)
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}


