name: Npm Package

on:
  push:
    # branches:
    #   - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i -g npm@latest
      - name: Bump version
        if: "'refs/heads/master' == github.ref || 'refs/heads/beta' == github.ref"
        uses: remorses/bump-version@js
        with:
          version_file: VERSION
          ignore: dist, esm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --access public --tag beta
        if: "'refs/heads/master' == github.ref || 'refs/heads/beta' == github.ref"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
